dist: xenial
sudo: required

before_install:
  - sudo ./install-dependencies.sh

install:
  - rm -rf public

script:
  - hugo

#  - rvm use default
#  - pushd public && htmlproofer . --check-html --disable-external --allow-hash-href --empty-alt-ignore && popd

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: psu-cmg/psu-cmg.github.io
  target_branch: master
  fqdn: cmg.psu.edu

env:
  global:
    - HUGO_RELEASE=0.50
    - RUBY_RELEASE=2.6.7
