# non-zero exit code in the following and the build is "errored"
#   - before_install
#   - install
#   - before_script
#
# non-zero exit code in the following and the build is "failed"
#   - script

dist: xenial
sudo: required

# non-zero exit code: build is "errored"
before_install:
  - sudo ./install-dependencies.sh

# non-zero exit code: build is "errored"
install:
  - rm -rf public

# non-zero exit code: build is "errored"
#before_script:
#  - sudo ./install-CA.sh

#script:
#  - /snap/bin/hugo

script:
  - hugo

#  - pushd public && htmlproofer --disable-external --allow-hash-href --alt-ignore /images/gopher-404.jpg --file-ignore /revealjs/ . && popd

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: psu-cmg/psu-cmg.github.io
  target_branch: master
  fqdn: cmg.psu.edu
