name: Build and Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_BUILD__NOKOGIRI: --use-system-libraries

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.50'

      - name: Build Site
        run: hugo

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: psu-cmg/psu-cmg.github.io
          publish_branch: master
          cname: cmg.psu.edu
          force_orphan: true

